print("=== Анализ последовательности ДНК ===")
dna = input("Введите последовательность ДНК: ").upper()
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
length = len(dna)
print(f"Подсчёт нуклеотидов: \nA {count_A}")
print(f"T {count_T}\nG {count_G}\nC {count_C}")
print(f"Общая длина: {length} нуклеотидов")